import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./../globals.css";
import Header from "../components/Header";



const noto =Noto_Sans({subsets:['latin'],weight:['200','400','600','800']});

export const metadata: Metadata = {
  title: "Calendo",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto.className} ${noto.className} antialiased`}>
        <main className="container">
        <Header/> 

        {children}
        </main>
      </body>
    </html>
  );
}
